-- 老库升级：评论楼中楼两级回复。可重复执行（MySQL 8.0.29+ 支持 IF NOT EXISTS）。
ALTER TABLE comments ADD COLUMN IF NOT EXISTS parent_id BIGINT NOT NULL DEFAULT 0;
ALTER TABLE comments ADD COLUMN IF NOT EXISTS reply_count BIGINT NOT NULL DEFAULT 0;
ALTER TABLE comments ADD COLUMN IF NOT EXISTS reply_to BIGINT NOT NULL DEFAULT 0;
ALTER TABLE comments ADD INDEX IF NOT EXISTS idx_parent (parent_id, id);
